//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _8osa.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_8osa.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming Languages.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-performance system programming.
        /// </summary>
        public static string Cpp_Desc {
            get {
                return ResourceManager.GetString("Cpp_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator: Bjarne Stroustrup. Used for: games, OS, browsers.
        /// </summary>
        public static string Cpp_Detail {
            get {
                return ResourceManager.GetString("Cpp_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful object-oriented language by Microsoft.
        /// </summary>
        public static string Csharp_Desc {
            get {
                return ResourceManager.GetString("Csharp_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator: Anders Hejlsberg. Used for: .NET, Unity, ASP.NET, MAUI.
        /// </summary>
        public static string Csharp_Detail {
            get {
                return ResourceManager.GetString("Csharp_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World:.
        /// </summary>
        public static string HelloWorldLabel {
            get {
                return ResourceManager.GetString("HelloWorldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write once, run anywhere.
        /// </summary>
        public static string Java_Desc {
            get {
                return ResourceManager.GetString("Java_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator: James Gosling. Used for: Android, enterprise, backend.
        /// </summary>
        public static string Java_Detail {
            get {
                return ResourceManager.GetString("Java_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language of the web.
        /// </summary>
        public static string JS_Desc {
            get {
                return ResourceManager.GetString("JS_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator: Brendan Eich. Used for: frontend, Node.js, React Native.
        /// </summary>
        public static string JS_Detail {
            get {
                return ResourceManager.GetString("JS_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great for data science and automation.
        /// </summary>
        public static string Python_Desc {
            get {
                return ResourceManager.GetString("Python_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator: Guido van Rossum. Used for: AI/ML, data analysis, Django.
        /// </summary>
        public static string Python_Detail {
            get {
                return ResourceManager.GetString("Python_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap a card for more info.
        /// </summary>
        public static string TapHint {
            get {
                return ResourceManager.GetString("TapHint", resourceCulture);
            }
        }
    }
}
